# Generated by Django 4.1.3 on 2022-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_date_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=9),
            preserve_default=False,
        ),
    ]
